image: python:3.6
definitions:
  steps:
    - step: &DeployStep
          name: DeployStep
          caches:
            - pip        
          script:
            - pip install "https://github.com/ansible/awx/archive/$AWX_VERSION.tar.gz#egg=awxkit&subdirectory=awxkit"
            - /bin/bash deploy/deploy.bash
pipelines:
  custom:
    deploy-to-production: 
    - step:
        <<: *DeployStep
        deployment: Production
  branches:
    master:
      - step:
          <<: *DeployStep
          deployment: Staging
    '{development,dev}':
      - step:
          <<: *DeployStep
          deployment: Development