export const iconNames = {
  0: { name: "google", color: "#3C5A99", displayName: "Google" },
  1: { name: "facebook", color: "#3C5A99", displayName: "Facebook" },
  2: { name: "youtube", color: "#ff0000", displayName: "You-Tube" },
  3: { name: "instagram", color: "#F77737", displayName: "Instagram" },
  4: { name: "qzone", color: "", displayName: "QZone" },
  5: { name: "weibo", color: "#df2029", displayName: "Weibo" },
  6: { name: "twitter", color: "#38A1F3", displayName: "Twitter" },
  7: { name: "reddit", color: "#FF5700", displayName: "Reddit" },
  8: { name: "pinterest", color: "#c8232c", displayName: "Pinterest" },
  9: { name: "ask.fm", color: "", displayName: "Ask.fm" },
  10: { name: "tumblr", color: "#34526f", displayName: "Tumblr" },
  11: { name: "flickr", color: "#ff0084", displayName: "Flickr" },
  12: { name: "google-plus", color: "#CC3333", displayName: "Google-Plus" },
  13: { name: "linkedin", color: "#0077B5", displayName: "Linkedin" },
  14: { name: "vk", color: "#4c75a3", displayName: "Vk" },
  15: { name: "odnoklassniki", color: "#ed812b", displayName: "Odnoklassniki" },
  16: { name: "meetup", color: "#e51937", displayName: "Meetup" },
  17: { name: "medium", color: "#00ab6c", displayName: "Medium" },
  18: { name: "trustpilot", color: "#000", displayName: "Trustpilot" },
  19: { name: "trustedshops", color: "#000", displayName: "Trustedshops" }
};
