//AUTH ACTION TYPES

export const LOGIN_INIT = "LOGIN_INIT";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const SIGNUP_INIT = "SIGNUP_INIT";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const TRUST_VOTE_INIT = "TRUST_VOTE_INIT";
export const TRUST_VOTE_SUCCESS = "TRUST_VOTE_SUCCESS";
export const TRUST_VOTE_FAILURE = "TRUST_VOTE_FAILURE";

export const LOGOUT = "LOGOUT";

export const SEND_TRUST_DATA_LATER = "SEND_TRUST_DATA_LATER";
export const REDIRECT_TO_LOGIN_WITH_EMAIL = "REDIRECT_TO_LOGIN_WITH_EMAIL";

export const ACTIVATE_USER_INIT = "ACTIVATE_USER_INIT";
export const ACTIVATE_USER_SUCCESS = "ACTIVATE_USER_SUCCESS";
export const ACTIVATE_USER_FAILURE = "ACTIVATE_USER_FAILURE";

export const VERIFY_RESET_PASSWORD_TOKEN_INIT =
  "VERIFY_RESET_PASSWORD_TOKEN_INIT";
export const VERIFY_RESET_PASSWORD_TOKEN_SUCCESS =
  "VERIFY_RESET_PASSWORD_TOKEN_SUCCESS";
export const VERIFY_RESET_PASSWORD_TOKEN_FAILURE =
  "VERIFY_RESET_PASSWORD_TOKEN_FAILURE";

//DOMAIN DATA TYPES
export const SET_DOMAIN_DATA_IN_REDUX = "SET_DOMAIN_DATA_IN_REDUX";
export const SET_DOMAIN_PROFILE_LOADER = "SET_DOMAIN_PROFILE_LOADER";
